import {currentCamera,updateSlicePreservingCamera} from './camera-update.mjs';
import {pbfSizeAdvice} from './import-limits.mjs';
import {installTooltips} from './tooltips.mjs';
import {slicePercent,bindTimePicking} from './time-selection.mjs';
import {createAnchorEditor} from './anchor-editor.mjs';
import {clock} from './engine.mjs';
import {meters} from './roads.mjs';
import {latestRenderer,sliceSelection} from './slice-player.mjs';
import {prepareSlices} from './slice.mjs';
import {createMap} from './map2d.js';
import {mapSurface} from './basemap.js';
import {createPlaneOverlay} from './plane-overlay.mjs';
const $=id=>document.getElementById(id),worker=new Worker('network-worker.js',{type:'module'});
const names={walk:'Walking',transit:'Transit + walking',bike:'Biking',drive:'Driving'},colors={walk:'#4ade80',transit:'#75b9ff',bike:'#c084fc',drive:'#a8adb5'};
const fields=['maxWalkMinutes','date','buffer','mode','walkSpeed','bikeSpeed','driveFactor'];
let roads,stops=[],meta,result,busy=true,feedReady=false,roadsReady=false,submitted,renderToken=0,baseCache=new Map(),sliceTrace=-1,pendingName='',camera={eye:{x:1.7,y:-1.9,z:1.2}};
let clearTimePicking=()=>{};
let customFeed=false,viewBounds,vehicleSlice,vehicleTrace=-1,getSlice,roadFile,committedSlice=50,renderedSlice=null;
const planeOverlay=createPlaneOverlay($('plot'));
const anchorEditor=createAnchorEditor($('anchorList'),()=>{mapView.setAnchors(params());status('Anchors changed. Calculate to apply the schedule.');},id=>mapView.select(id));
const mapView=createMap((id,lon,lat)=>{if(busy){mapView.setAnchors(params());return}anchorEditor.setPosition(id,lon,lat)},id=>{if(!id)anchorEditor.clearSelection()});
function clearResult(){clearTimePicking();clearTimePicking=()=>{};planeOverlay.clear();slicePlayer.cancel();renderedSlice=null;getSlice=null;result=null;viewBounds=null;mapView.clear();Plotly.purge('plot');$('lastImage').hidden=true;$('activityInfo').textContent='No calculated activity window.';$('sliceCount').textContent='No calculated slice';$('mapStatus').textContent='3D basemap pending calculation';}
$('fitMap').onclick=()=>{const a=anchorEditor.values().filter(a=>Number.isFinite(+a.lon)&&Number.isFinite(+a.lat));if(a.length)mapView.fit([Math.min(...a.map(a=>+a.lon))-.002,Math.min(...a.map(a=>+a.lat))-.002,Math.max(...a.map(a=>+a.lon))+.002,Math.max(...a.map(a=>+a.lat))+.002])};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activityClock(t){const n=Math.round(t);return clock(n)+':'+String(n%60).padStart(2,'0')}
function status(message,error=false){if(busy&&!error)$('progressLabel').textContent=message;$('status').textContent=message;$('status').classList.toggle('error',error)}
function lock(value){busy=value;$('calculationProgress').hidden=!value;$('status').hidden=value;if(value)$('progressLabel').textContent='Loading data…';if(!value){$('calculationProgress').hidden=true;$('plot').setAttribute('aria-busy','false');}for(const id of ['calculate','upload','roadUpload','cota','loadStreets','slice','basemap','roads','ribbons','transit',...fields])$(id).disabled=value;$('loadStreets').disabled=value||!roadFile;$('calculate').disabled=value||!feedReady||!roadsReady;$('calculate').textContent=value?'Working…':'Calculate prism ↗';$('photo').disabled=$('export').disabled=value||!result;anchorEditor.lock(value)}
function params(){return {...Object.fromEntries(fields.map(k=>[k,$(k).value])),walkSpeed:Number($('walkSpeed').value)*3.6,bikeSpeed:Number($('bikeSpeed').value)*3.6,anchors:anchorEditor.values()}}
$('maxWalkMinutes').onchange=()=>status('Walking limit changed. Calculate to apply it.');
function calculate(){if(busy||!feedReady||!roadsReady)return;if(!$('controls').reportValidity())return;mapView.finishPlacement();submitted=params();lock(true);$('progressLabel').textContent='Calculating network reachability…';$('calculationProgress').hidden=false;$('plot').setAttribute('aria-busy','true');status('Calculating forward and backward network reachability…');worker.postMessage({type:'calculate',params:submitted})}
const allowed=new Set(['stops','trips','stop_times','calendar','calendar_dates','frequencies','transfers','pathways','shapes','agency']);
async function unzip(bytes){let total=0;const files=await new Promise((resolve,reject)=>fflate.unzip(new Uint8Array(bytes),{filter:f=>{const name=f.name.split('/').pop().replace(/\.txt$/i,'');if(!allowed.has(name))return false;total+=f.originalSize;if(total>250*1048576)throw Error('GTFS tables exceed the 250 MB limit.');return true}},(e,d)=>e?reject(e):resolve(d)));const decoded={};for(const [name,b]of Object.entries(files)){const key=name.split('/').pop().replace(/\.txt$/i,'');if(decoded[key])throw Error('Duplicate GTFS table '+key);decoded[key]=new TextDecoder().decode(b)}return decoded}
async function loadCota(){customFeed=false;$('pbfAdvice').textContent='';clearResult();anchorEditor.reset(-83.00090,39.96278);mapView.setAnchors(params());lock(true);status('Loading COTA and Columbus OSM PBF…');try{const [g,r]=await Promise.all([fetch('data/cota.gtfs.zip'),fetch('data/columbus.osm.pbf')]);if(!g.ok||!r.ok)throw Error('Default data unavailable. Import a GTFS ZIP and OSM PBF.');const [files,blob]=await Promise.all([g.arrayBuffer().then(unzip),r.blob()]);roadFile=new File([blob],'columbus.osm.pbf');feedReady=roadsReady=false;pendingName='Columbus COTA';worker.postMessage({type:'load',files,preferredDate:$('date').value});worker.postMessage({type:'pbf',file:roadFile,bbox:[39.79,-83.21,40.20,-82.73]})}catch(e){lock(false);status(e.message,true)}}
worker.onmessage=async({data})=>{if(data.type==='pbfProgress'){status(data.pass===3?'Building the road graph from PBF…':`Reading OSM PBF · pass ${data.pass}/2 · ${data.percent}%`);return}if(data.type==='error'){clearResult();lock(false);status(data.message,true);return}if(data.type==='roadsReady'){clearResult();roads=data.roads;roadsReady=true;$('roadInfo').textContent=`${roads.nodes.length.toLocaleString()} road vertices · ${roads.meta?.format||'OSM'} · ${roads.meta?.file||'road network'}`;lock(false);if(feedReady)calculate();return}if(data.type==='loaded'){stops=data.stops;meta=data.meta;feedReady=true;$('agencyCredit').textContent=meta.agency;if(customFeed){let x=0,y=0;for(const s of stops){x+=+s.stop_lon;y+=+s.stop_lat}x/=stops.length;y/=stops.length;const center=stops.reduce((a,b)=>Math.hypot(+a.stop_lon-x,+a.stop_lat-y)<Math.hypot(+b.stop_lon-x,+b.stop_lat-y)?a:b);anchorEditor.reset(+center.stop_lon,+center.stop_lat);mapView.setAnchors(params());mapView.map.setView([+center.stop_lat,+center.stop_lon],13);lock(false);status('GTFS loaded. Set anchors on the map, then choose an OSM PBF for this region.');$('roadInfo').textContent='OSM PBF needed for this feed';}$('feed').textContent=`${pendingName||meta.agency} · ${stops.length.toLocaleString()} stops`;$('timezone').textContent=`${meta.timezone}`;if(meta.suggestedDate)$('date').value=meta.suggestedDate;if(roadsReady){lock(false);calculate()}return}
 $('progressLabel').textContent='Preparing 2D and 3D views…';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));slicePlayer.cancel();result=data.result;getSlice=prepareSlices(result,roads);$('activityInfo').textContent=result.connected?`${result.anchors.length} anchors · all required stays enforced`:'No journey satisfies all anchors and constraints.';viewBounds=bounds();mapView.setAnchors(result.params);mapView.fit(viewBounds);try{await draw();let message=result.connected?`Prism satisfies all ${result.anchors.length} anchors and the walking limit.`:'No feasible journey satisfies the time, stay and walking constraints.';if(result.stats.boundary)message+=' Reaches the road-extract boundary: coverage may be truncated.';status(message,!result.connected)}catch(e){status('Rendering failed: '+e.message,true)}finally{lock(false)}};
worker.onerror=()=>{lock(false);status('The calculation worker stopped. Reload and try a smaller dataset.',true)};
function bounds(){const a=result.anchors.map(a=>[a.lon,a.lat]);let minx=Math.min(...a.map(p=>p[0])),maxx=Math.max(...a.map(p=>p[0])),miny=Math.min(...a.map(p=>p[1])),maxy=Math.max(...a.map(p=>p[1]));for(const i of result.roadEdges){const e=roads.edges[i];for(const n of [e[0],e[1]]){const p=roads.nodes[n];minx=Math.min(minx,p[0]);maxx=Math.max(maxx,p[0]);miny=Math.min(miny,p[1]);maxy=Math.max(maxy,p[1])}}for(const r of result.rides)for(const p of r.path){minx=Math.min(minx,p[0]);maxx=Math.max(maxx,p[0]);miny=Math.min(miny,p[1]);maxy=Math.max(maxy,p[1])}const dx=Math.max(.003,(maxx-minx)*.05),dy=Math.max(.003,(maxy-miny)*.05);return [minx-dx,miny-dy,maxx+dx,maxy+dy]}
function line(color,width,name){return {type:'scatter3d',mode:'lines',x:[],y:[],z:[],text:[],hovertemplate:'%{text}<extra></extra>',line:{color,width},name,showlegend:false}}
function addLine(t,points,labels){for(let i=0;i<points.length;i++){t.x.push(points[i][0]);t.y.push(points[i][1]);t.z.push(points[i][2]);t.text.push(labels?.[i]||'')}t.x.push(null);t.y.push(null);t.z.push(null);t.text.push('')}
function roadCost(e){return e[2]*3.6/(result.mode==='drive'?e[4]*+result.params.driveFactor:result.mode==='bike'?+result.params.bikeSpeed:+result.params.walkSpeed)}
function roadRibbons(){const t={type:'mesh3d',x:[],y:[],z:[],i:[],j:[],k:[],color:colors[result.mode],opacity:.14,flatshading:true,hoverinfo:'none',name:'Feasible street travel-time bands',showscale:false},lower=line(colors[result.mode],2,'Earliest feasible traversal');const bands=result.roadBands,stride=Math.max(1,Math.ceil(bands.length/24000));for(let n=0;n<bands.length;n+=stride){const band=bands[n],e=roads.edges[band.road],a=roads.nodes[e[0]],b=roads.nodes[e[1]],c=roadCost(e),early=band.early,late=band.late,lo=(early-result.start)/60,hi=(late-result.start)/60,off=t.x.length;for(const p of [[...a,lo],[...b,lo+c/60],[...b,hi],[...a,hi-c/60]]){t.x.push(p[0]);t.y.push(p[1]);t.z.push(p[2])}t.i.push(off,off);t.j.push(off+1,off+2);t.k.push(off+2,off+3);addLine(lower,[[...a,lo],[...b,lo+c/60]],['Earliest road traversal','Earliest road traversal'])}return [t,lower]}
function slice(value=committedSlice){const at=result.start+(result.end-result.start)*value/100,z=(at-result.start)/60,t=line('#e86100',4,'Time-slice PPA'),g=getSlice(at);t.hoverinfo='none';delete t.hovertemplate;for(const [a,b]of g.segments){t.x.push(a[0],b[0],null);t.y.push(a[1],b[1],null);t.z.push(z,z,null)}vehicleSlice={type:'scatter3d',mode:'markers',x:g.vehicles.map(p=>p[0]),y:g.vehicles.map(p=>p[1]),z:g.vehicles.map(()=>z),marker:{size:4,color:'#ffad70'},hovertemplate:'Feasible on-board position<extra></extra>',showlegend:false};mapView.show(g);$('mapTime').textContent=clock(at);$('sliceCount').textContent=g.activities.length?`At required anchor · ${clock(at)}`:`${g.count.toLocaleString()} network segments · ${g.vehicles.length} transit positions`;return t}
function slicePlane(b){const z=(result.end-result.start)/60*committedSlice/100;return {type:'mesh3d',x:[b[0],b[2],b[2],b[0]],y:[b[1],b[1],b[3],b[3]],z:[z,z,z,z],i:[0,0],j:[1,2],k:[2,3],color:'#92a6c9',opacity:.10,hoverinfo:'skip',showlegend:false}}
async function draw(){if(!result)return;const token=++renderToken,b=bounds(),traces=[];$('modeColor').style.background=colors[result.mode];
 if($('basemap').checked){$('mapStatus').textContent='Loading map tiles…';try{const key=b.map(x=>x.toFixed(5)).join(',');if(!baseCache.has(key)){if(baseCache.size>=2)baseCache.delete(baseCache.keys().next().value);baseCache.set(key,mapSurface(b))}const surface=await baseCache.get(key);if(token!==renderToken)return;traces.push(surface);$('mapStatus').textContent='OpenStreetMap basemap'}catch{$('mapStatus').textContent='Map tiles unavailable · showing street network'}}else $('mapStatus').textContent='Street-network basemap';
 const base=line($('basemap').checked?'#425269':'#506783',1,'Street network');if($('roads').checked){const stride=Math.max(1,Math.ceil(roads.edges.length/70000));for(let j=0;j<roads.edges.length;j+=stride){const e=roads.edges[j],a=roads.nodes[e[0]],d=roads.nodes[e[1]];if(a[0]<b[0]||a[0]>b[2]||a[1]<b[1]||a[1]>b[3])continue;addLine(base,[[...a,-.05],[...d,-.05]],['OpenStreetMap street','OpenStreetMap street'])}}traces.push(base);
 if($('ribbons').checked)traces.push(...roadRibbons());
 const transit=line('#ffad70',4,'Transit');if($('transit').checked)for(const r of result.rides){let cumulative=[0];for(let i=1;i<r.path.length;i++)cumulative.push(cumulative.at(-1)+meters(r.path[i-1],r.path[i]));const total=cumulative.at(-1)||1;addLine(transit,r.path.map((p,i)=>[...p,(r.depart+(r.arrive-r.depart)*cumulative[i]/total-result.start)/60]),r.path.map(()=>`Route ${esc(r.route)} · ${clock(r.depart)}–${clock(r.arrive)}<br>Trip ${esc(r.trip)}`))}traces.push(transit);
 const anchors=result.anchors;
 traces.push({type:'scatter3d',mode:'markers+text',x:anchors.map(a=>a.lon),y:anchors.map(a=>a.lat),z:anchors.map(a=>(a.start-result.start)/60),text:anchors.map((a,i)=>esc(String(i+1)+' · '+a.label)),textposition:'top center',textfont:{color:'#ffffff',size:12},marker:{size:7,color:anchors.map((a,i)=>i===0?'#ffad70':i===anchors.length-1?'#ff9466':'#ffc044')},hovertemplate:'%{text}<br>%{x:.5f}, %{y:.5f}<extra></extra>',showlegend:false});
 for(const activity of result.activities||[])if(activity.feasible&&activity.duration>0){const stay=line('#ffc044',9,'Required stay');addLine(stay,[[activity.lon,activity.lat,(activity.earliestStart-result.start)/60],[activity.lon,activity.lat,(activity.latestEnd-result.start)/60]],[esc(activity.name)+' · '+activity.duration/60+' min','Stay ends']);traces.push(stay)}
 renderedSlice=committedSlice;showSliceTime(+$('slice').value);sliceTrace=traces.length;traces.push(slice());vehicleTrace=traces.length;traces.push(vehicleSlice);const duration=(result.end-result.start)/60,ticks=[];for(let t=0;t<=duration;t+=Math.max(5,Math.ceil(duration/6/5)*5))ticks.push(t);const ax={gridcolor:'#314159',zerolinecolor:'#42516a',color:'#b7c9df',showbackground:false};
 const snapshot=currentCamera($('plot'));if(snapshot)camera=snapshot;
 await Plotly.react('plot',traces,{paper_bgcolor:'#0b2341',plot_bgcolor:'#0b2341',font:{color:'#c4d2e4'},margin:{l:0,r:0,b:30,t:25},uirevision:'network-prism',annotations:[{text:`© OpenStreetMap contributors · ${esc(meta.agency)} · Prism Lab`,x:.99,y:.01,xref:'paper',yref:'paper',showarrow:false,xanchor:'right',yanchor:'bottom',font:{size:9}}],scene:{camera,annotations:(result.activities||[]).filter(a=>a.feasible&&a.duration>0).map(a=>({x:a.lon,y:a.lat,z:((a.earliestStart+a.latestEnd)/2-result.start)/60,text:`${a.anchorIndex+1} · ${a.duration/60} min`,showarrow:true,arrowhead:2,ax:50,ay:-25,font:{size:12,color:'#ffe2a1'},bgcolor:'#183859',bordercolor:'#ffc044',borderpad:4})),xaxis:{...ax,title:'Longitude',range:[b[0],b[2]]},yaxis:{...ax,title:'Latitude',range:[b[1],b[3]]},zaxis:{...ax,title:'Time ↑',tickvals:ticks,ticktext:ticks.map(t=>clock(result.start+t*60)),range:[-1,duration]},aspectmode:'manual',aspectratio:{x:1,y:Math.min(2,(b[3]-b[1])/((b[2]-b[0])*Math.cos((b[1]+b[3])/2*Math.PI/180))),z:1.15}}},{responsive:true,doubleClick:false,displaylogo:false,displayModeBar:false,modeBarButtonsToRemove:['toImage']});
 planeOverlay.configure(b,duration,+$('slice').value);
 clearTimePicking();clearTimePicking=bindTimePicking($('plot'),z=>{if(!result||busy)return;const value=slicePercent(z,(result.end-result.start)/60);if(value===null)return;$('slice').value=value;committedSlice=value;selection.change(value)});
}
$('controls').onsubmit=e=>{e.preventDefault();calculate()};$('cota').onclick=loadCota;$('mode').onchange=()=>calculate();
for(const id of ['basemap','roads','ribbons','transit'])$(id).onchange=()=>draw().catch(e=>status(e.message,true));
function showSliceTime(value){if(result)$('sliceLabel').textContent=clock(result.start+(result.end-result.start)*value/100)}
const slicePlayer=latestRenderer(async(value,version)=>{
 if(!result||busy||sliceTrace<0||!slicePlayer.isCurrent(version)||value===renderedSlice)return;
 const started=performance.now(),t=slice(value);
 await updateSlicePreservingCamera(Plotly,$('plot'),{x:[t.x,vehicleSlice.x],y:[t.y,vehicleSlice.y],z:[t.z,vehicleSlice.z]},[sliceTrace,vehicleTrace]);
 if(slicePlayer.isCurrent(version)){renderedSlice=value;$('slice').dataset.renderMs=(performance.now()-started).toFixed(1)}
},e=>status('Time-slice update failed: '+e.message,true));
const selection=sliceSelection(value=>{showSliceTime(value);planeOverlay.move(value)},value=>slicePlayer.push(value));
$('slice').oninput=()=>{if(!result||busy)return;selection.input(+$('slice').value)};
$('slice').onchange=()=>{if(!result||busy)return;committedSlice=+$('slice').value;selection.change(committedSlice)};
$('reset').onclick=()=>{camera={eye:{x:1.7,y:-1.9,z:1.2}};if(result)Plotly.relayout('plot',{'scene.camera':camera})};
$('photo').onclick=async()=>{if(!result)return;$('photo').disabled=true;try{await slicePlayer.whenIdle();const graph=$('plot'),exportLayout=structuredClone(graph.layout);exportLayout.scene.camera=graph._fullLayout.scene._scene.getCamera();const png=await Plotly.toImage({data:[...structuredClone(graph.data),slicePlane(viewBounds)],layout:exportLayout},{format:'png',width:2200,height:1600});const link=$('lastImage');link.href=png;link.download=`prism-${result.mode}-${result.params.date}.png`;link.hidden=false;link.click();status('PNG ready at 2200 × 1600 pixels. Use Download PNG if your browser did not save it automatically.')}catch(e){status('Image export failed: '+e.message,true)}finally{$('photo').disabled=false}};
$('export').onclick=()=>{if(!result)return;const data={model:'Coordinate-anchored multimodal network prism',parameters:result.params,roadSource:roads.meta,assumptions:'Approximate 150 m anchor snapping; static modal speeds; no signals, turn restrictions, parking or GTFS transfer-specific rules.',anchors:result.anchors,activities:result.activities,stats:result.stats,stopIntervals:result.intervals,transit:result.rides,roadSegments:result.roadBands.map(band=>{const e=roads.edges[band.road];return {from:roads.nodes[e[0]],to:roads.nodes[e[1]],travelSeconds:roadCost(e),earliestDeparture:band.early,latestArrival:band.late,phase:band.phase}})};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=`prism-${result.mode}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;lock(true);status('Reading GTFS ZIP…');try{if(f.size>80*1048576)throw Error('GTFS ZIP limit: 80 MB.');pendingName=f.name;const files=await unzip(await f.arrayBuffer());customFeed=true;$('pbfAdvice').textContent='';roadFile=null;feedReady=roadsReady=false;clearResult();worker.postMessage({type:'load',files,preferredDate:$('date').value})}catch(e){lock(false);status(e.message,true)}finally{e.target.value=''}};
function importPbf(){if(busy||!roadFile)return;const b=mapView.map.getBounds(),bbox=[b.getSouth(),b.getWest(),b.getNorth(),b.getEast()];if(meters([bbox[1],bbox[0]],[bbox[3],bbox[0]])>60000||meters([bbox[1],bbox[0]],[bbox[1],bbox[2]])>60000){status('Zoom in: use a study area at most 60 km across for browser PBF processing.',true);return}lock(true);status('Opening OSM PBF in the background…');worker.postMessage({type:'pbf',file:roadFile,bbox})}
$('roadUpload').onchange=e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(!/\.pbf$/i.test(f.name)){status('Choose an .osm.pbf file from an OSM regional download provider.',true);return}$('pbfAdvice').textContent=pbfSizeAdvice(f);roadFile=f;$('loadStreets').disabled=false;importPbf()};
$('loadStreets').onclick=importPbf;
if(document.modelContext?.registerTool)try{document.modelContext.registerTool({name:'read_prism',description:'Read the calculated multimodal prism and visible control values.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({currentControls:params(),calculatedParameters:result?.params,connected:result?.connected,feasibleStops:result?.stopIds.length,roadKm:result?.roadKm,transitSegments:result?.rides.length,stats:result?.stats,busy})})}catch{}
installTooltips();
loadCota();
