import {saveView,validateView} from './saved-view.mjs';
import {roadsFromPbf} from './pbf.mjs';
import {csv,active} from './engine.mjs';
import {prepareFeed,multimodal} from './multimodal.mjs';
let prepared,roads;let snapCache=new Map();
self.onmessage=async({data})=>{try{
 if(data.type==='view'){const text=await data.file.text();const snapshot=validateView(JSON.parse(text));self.postMessage({type:'viewReady',snapshot});return}
 if(data.type==='saveView'){const json=JSON.stringify(saveView(data.result,data.roads,data.meta,data.view));self.postMessage({type:'viewExport',json});return}
 if(data.type==='pbf'){const candidate=await roadsFromPbf(data.file,data.bbox,progress=>self.postMessage({type:'pbfProgress',...progress}));roads=candidate;snapCache=new Map();self.postMessage({type:'roadsReady',roads});return}
 if(data.type==='load'){const feed={};for(const [name,text]of Object.entries(data.files))feed[name]=csv(text);for(const name of ['stops','trips','stop_times'])if(!feed[name]?.length)throw Error('Missing '+name+'.txt');if(feed.frequencies?.length)throw Error('Frequency-based service is not supported.');feed.calendar??=[];feed.calendar_dates??=[];if(!feed.calendar.length&&!feed.calendar_dates.length)throw Error('A service calendar is required.');for(const s of feed.stops)if(!s.stop_id||!s.stop_lat?.trim()||!s.stop_lon?.trim()||!Number.isFinite(+s.stop_lat)||!Number.isFinite(+s.stop_lon))throw Error('Invalid GTFS stop coordinates.');let suggestedDate=data.preferredDate;const hasService=d=>d&&active(feed,d).size>0;if(!hasService(suggestedDate)){const dates=[...feed.calendar.map(r=>r.start_date),...feed.calendar_dates.filter(r=>r.exception_type==='1').map(r=>r.date)].sort();suggestedDate=null;for(const date of dates){const start=new Date(date.replace(/(\d{4})(\d{2})(\d{2})/,'$1-$2-$3')+'T12:00:00Z');for(let i=0;i<14;i++){const day=new Date(+start+i*86400000).toISOString().slice(0,10);if(hasService(day)){suggestedDate=day;break}}if(suggestedDate)break}}const next=prepareFeed(feed);prepared=next;snapCache=new Map();self.postMessage({type:'loaded',stops:feed.stops,meta:{suggestedDate,agency:feed.agency?.[0]?.agency_name||'GTFS feed',timezone:feed.agency?.[0]?.agency_timezone||'agency local time',trips:feed.trips.length,stopTimes:feed.stop_times.length,dates:[...feed.calendar.map(r=>r.start_date),...feed.calendar_dates.filter(r=>r.exception_type==='1').map(r=>r.date)].sort(),endDates:[...feed.calendar.map(r=>r.end_date),...feed.calendar_dates.filter(r=>r.exception_type==='1').map(r=>r.date)].sort(),transferRules:feed.transfers?.length||0}});return}
 if(!prepared||!roads)throw Error('Load both GTFS and road network data first.');const result=multimodal(prepared,roads,data.params,snapCache);self.postMessage({type:'result',result});
 }catch(e){self.postMessage({type:'error',operation:data.type,message:String(e?.message||e)})}};
